### PR TITLE
Adding KievII library.

### PR DESCRIPTION
**Pull request by cristiano-belloni**
Hi, I'd like to add my web audio library (KievII) to your nice list. You can find info on the library in ist homepage: http://kievii.net/.
Thanks and regards,
Cristiano.

### CODE REVIEW

**Comment by tomdale** [comment]
Hey, this looks great. Cristiano, would you mind adding some more detailed size information? Minimum and maximum? Thanks!

**Comment by cristiano-belloni** [comment]
Thank you for the feedback, updated min/max sizes

**Comment by cristiano-belloni** [comment]
Yeah, and put them in a string. In my defense, I'm very tired :D

**Comment by tomdale** [comment]
Thanks!

**Pull request closed without merging**
